### ISSUE TITLE
Support writing to named loggers

### ISSUE THREAD

**Issue by hackquest-grid** [go-clog/clog#20]
If I want to use logging for different modules, I would have destinations (like file) depending on the module.

Has it been planned or envisaged to write to a specific logger and not to all managed loggers ?

For example, I would create a console and a file logged for the main part of an application, but also would have a specific logger for a module (let's call it "module"). That would be convenient to have InfoTo(), WarnTo(), etc... for this:
```go
log.NewFileWithName("module", 100, log.FileConfig{
  Level: log.LevelInfo,
  Filename: "module.log"
})

log.InfoTo("module", "log this")
log.WarnTo("module", "warn this")
```
A complete management of different logger sources with associated destinations would be better, but I think it's a good compromise to add such a functionnality without breaking compatibility.

**Comment by unknwon** [comment]
Implemented in https://github.com/go-clog/clog/pull/21.
