### ISSUE TITLE
[BUG] First log not written

### ISSUE THREAD

**Issue by karitham** [go-clog/clog#22]
The first log is not written everytime
```go
package main

import log "unknwon.dev/clog/v2"

func init() {
	if err := log.NewConsole(); err != nil {
                panic("unable to create new logger: " + err.Error())
        }
}

func main() { log.Trace("This will not print") } // will not print anything
```

But everything get written correctly once you trigger a new one
```go
func main() {
       log.Trace("This will print")
       log.Trace("This will print too")
}
```

EDIT : after some more testing I found the behavior to be inconsistant,
I ran the same program around 5 times and had different results 
```go
func main() {
	log.Trace("something")
	log.Trace("something")
}
```
![image](https://user-images.githubusercontent.com/57440386/103098909-cabf0400-460c-11eb-9bcb-a0666554a4cd.png)

**Comment by unknwon** [comment]
Hey, you need to call `log.Stop` before exit: https://github.com/go-clog/clog#clean-exit
