### ISSUE TITLE
Unexpected output

### ISSUE THREAD

**Issue by cup** [go-clog/clog#9]
Using this file:

~~~go
package main
import aa "gopkg.in/clog.v1"
func main() {
   aa.New(aa.CONSOLE, aa.ConsoleConfig{})
   aa.Info("bbbbb")
   aa.Info("ccccc")
}
~~~

I get this result:

~~~
2019/06/14 20:38:47 [ INFO] bbbbb
~~~

Notice only one message is printed.

**Comment by Unknwon** [comment]
Thanks for the feedback!

Forgot to mention in the REMADE, you should use [`Shudown`](https://godoc.org/gopkg.in/clog.v1#Shutdown) function before exit to make sure no message losy.

**Comment by Unknwon** [comment]
Docs are now added: https://github.com/go-clog/clog/blob/master/README.md#clean-shutdown
